### ISSUE TITLE
Is it possible to use this on an express router?

### ISSUE THREAD

**Issue by prashcr** [olalonde/express-websocket#2]
This worked really nice on an express `app`, and I want to be able to use it on a `router`. I kept getting a `400` error when I tried it on a router.

**Comment by olalonde** [comment]
I'm not sure it works. Can you give some example code?

**Comment by prashcr** [comment]
```
var express = require('express');
var http = require('http');
var ws = require('ws');

var handleUpgrade = require('express-websocket');

var app = express();
var server = http.createServer(app);
var wss = new ws.Server({ noServer: true });
var thing = express.Router();

app.use('/thing', thing)

thing.use('/websocket', function (req, res, next) {
  res.websocket(function (ws) {
    // Optional callback
    ws.send('hello');
  });
});

server.on('upgrade', handleUpgrade(app, wss));

server.listen(3000);
```

**Comment by olalonde** [comment]
So `http://localhost:3000/thing/websocket` doesn't open a websocket connection? weird, I'll have to check this later, I would have expected this to work.

**Comment by prashcr** [comment]
Never mind, I think I made a mistake in my code elsewhere, because it does work when I tested it with a simple example just now.
